version: '3.9'
services:
  database:
    container_name: api_database
    image: postgres
    restart: always
    networks:
      - db
    env_file:
      - .env.sample
    environment:
      POSTGRES_USER : usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: database
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

networks:
  db:
volumes:
  db-data: